### ISSUE TITLE
terminate called after throwing an instance of 'nlohmann::detail::parse_error'

### ISSUE THREAD

**Issue by ghost** [mr-pandabear/panda-coin#127]
After build I try starting.  I get this errors.

---------------------------------------------------------------------------------------------------------------------------------------------

"pool@pool:~ /pandanite/bin$ ./keygen
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
pool@pool:~ /pandanite/bin$ ./server
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
pool@pool:~ /pandanite/bin$ ./cli
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
pool@pool:~ /pandanite/bin$"

**Comment by J-Ttt** [comment]
Do ./bin/server from pandanite folder instead of ./server inside the bin folder. Same for keygen etc.
