### ISSUE TITLE
Why do I have such a large number of rejects?

### ISSUE THREAD

**Issue by Volk-khan** [mr-pandabear/panda-coin#19]
![image](https://user-images.githubusercontent.com/87937901/147931724-40238802-5f88-493d-9cf4-719100194c17.png)

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/147939950-f7ad4a65-7c02-4b1b-bf74-3ff43cbf6784.png)

**Comment by Volk-khan** [comment]
![image](https://user-images.githubusercontent.com/87937901/147942670-9ee35a43-7113-47b4-a2c9-7a1575a28891.png)

**Comment by mr-pandabear** [comment]
The block mint time is only 30 seconds, so if there are a lot of competing submissions the first one will win. Invalid block ID typically means the tip of the chain has already exceeded the ID of the block that was mined.

**Comment by mr-pandabear** [comment]
Note: We discovered a hack recently where miners were submitting invalid timestamps in the future. This led the tip of the chain to be slightly ahead causing mined blocks by other miners to get rejected due to "BLOCK_TIMESTAMP_TOO_OLD" error. We have updated the servers to fix this vulnerability.
